### ISSUE TITLE
lag structure and autocorrelation of residuals 

### ISSUE THREAD

**Issue by msh855** [pastas/metran#15]
Hi, 
Good work. 

Wondering if the metran only assumes AR(1) process. 

statsmodels have more flexible DFM configurations (see [here ](http://www.chadfulton.com/topics/statespace_large_dynamic_factor_models.html)an example), but they lack the ability to determine the optimal lags and numbers of structures.

**Comment by dbrakenhoff** [comment]
Hi @msh855, you are correct that metran only assumes the AR(1) process. That's about as far as my knowledge goes at this moment. 

@wlberendrecht wrote the original code, so he might be able to elaborate more on that subject.

**Comment by dbrakenhoff** [comment]
Which version of pastas are you on? 

```python
import pastas as ps

ps. __version__
```

Perhaps try upgrading?

`pip install pastas --upgrade`

**Comment by wlberendrecht** [comment]
Ha David,

Ik ben nu net met vakantie dus ik kan helaas niet op korte termijn reageren. 1 augustus ben ik weer terug en aan het werk.

Maar het klopt inderdaad dat we nu uitgaan van ar(1).

Groet,
Wilbert

Op 23 jun. 2023 om 14:02 heeft Davíd Brakenhoff ***@***.***> het volgende geschreven:

﻿

Hi @msh855<https://github.com/msh855>, you are correct that metran only assumes the AR(1) process. That's about as far as my knowledge goes at this moment.

@wlberendrecht<https://github.com/wlberendrecht> wrote the original code, so he might be able to elaborate more on that subject.

**Comment by martinvonk** [comment]
Maar het klopt inderdaad dat we nu uitgaan van ar(1).
