### ISSUE TITLE
Bug in kalmanfilter - decompose

### ISSUE THREAD

**Issue by bdestombe** [pastas/metran#8]
https://github.com/pastas/metran/blob/ac3c74ceedb75447243e369b3ba771e48099f00e/metran/kalmanfilter.py#L582

An error occurs here for `ncdf>1`, as the lists produced by the loop are `ncdf` times too long. Consider the following example:
```
a = [[]] * 2
a[0].append([0])
print(a)
```
I think the code in metran expects `[[[0]], [[]]]` to be printed, but instead `[[[0]], [[0]]]` is printed.

In which case `decompose_simulation` retrieves `cdf_means` that are too long. Or it could definitely be the case that I don't understand the code..

**Comment by dbrakenhoff** [comment]
Closed by #9
